version: "3.5"
services:
  web:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /home/lml/app
      - type: volume
        source: deps
        target: /home/lml/app/deps
      - type: volume
        source: build
        target: /home/lml/app/build
    environment:
      - DATABASE_URL=postgresql://localhost/dyn_qrcode_dev?user=postgres&password=postgres
    depends_on:
      - db
    ports:
      - "4000:4000"
    command: './run.sh'
  db:
    image: postgres:11.4-alpine
    command: 'postgres -c "max_connections=200"'
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
volumes:
  postgres-data:
  deps:
  build: